# Generated by Django 3.1.2 on 2020-10-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='roleFunction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagesApp.function'),
        ),
    ]
