# Generated by Django 3.1.2 on 2020-10-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesApp', '0002_role_rolefunction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='functionName',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
