# Generated by Django 3.1.2 on 2020-10-19 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagesApp', '0004_auto_20201019_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='functionName',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleFunction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagesApp.function'),
        ),
    ]
