# Generated by Django 3.1.2 on 2020-10-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesApp', '0005_auto_20201019_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='functionName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
