# Generated by Django 3.1.3 on 2020-11-10 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidateId', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=300)),
                ('email', models.EmailField(default='', max_length=50)),
                ('interestedRole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagesApp.role')),
            ],
        ),
    ]
