# Generated by Django 3.1.2 on 2020-10-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateApp', '0004_auto_20201020_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='firstName',
            field=models.CharField(default='', max_length=300),
        ),
    ]
