# Generated by Django 3.1.2 on 2020-10-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='expertId',
            field=models.UUIDField(default='2B8E65', editable=False, primary_key=True, serialize=False),
        ),
    ]
