# Generated by Django 3.1.3 on 2020-11-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertApp', '0002_auto_20201110_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='linkedInUrl',
            field=models.URLField(blank=True, default='', max_length=400, null=True),
        ),
    ]
