# Generated by Django 3.1.2 on 2020-10-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertApp', '0002_auto_20201016_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='expertId',
            field=models.UUIDField(default='1355C4', editable=False, primary_key=True, serialize=False),
        ),
    ]
