# Generated by Django 3.1.3 on 2020-11-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertApp', '0003_auto_20201110_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='yearsInterviewedFor',
            field=models.CharField(blank=True, choices=[('lessThanOne', 'Less than 1 year'), ('oneToThree', '1 - 3 years'), ('threeToFive', '3 - 5 years'), ('fiveToTen', '5 - 10 years'), ('moreThanTen', 'More than 10 years')], default='', max_length=12, null=True),
        ),
    ]
