# Generated by Django 3.1.3 on 2020-11-12 21:52

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('expertApp', '0003_auto_20201112_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='imageProfile',
            field=models.ImageField(blank=True, default='./mockWizProject/static/images/default.png', upload_to='expert/profilePicture'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='jobTitle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='expert',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='expert',
            name='phoneNumber',
            field=phone_field.models.PhoneField(blank=True, default='', help_text='Contact phone number', max_length=31),
        ),
    ]
