# Generated by Django 3.1.3 on 2020-11-10 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagesApp', '0001_initial'),
        ('expertApp', '0004_auto_20201110_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='expertiseFunction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pagesApp.function'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='linkedInUrl',
            field=models.URLField(default='', max_length=400),
        ),
    ]
