# Generated by Django 3.1.3 on 2020-11-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertApp', '0004_auto_20201112_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='expert',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='expert',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
