# Generated by Django 3.1.3 on 2020-11-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertApp', '0005_auto_20201116_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
