# Generated by Django 3.1.3 on 2020-11-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertApp', '0006_auto_20201110_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='approved',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='expert',
            name='yearsInterviewedFor',
            field=models.CharField(choices=[('', 'Years of interviewing experience'), ('lessThanOne', 'Less than 1 year'), ('oneToThree', '1 - 3 years'), ('threeToFive', '3 - 5 years'), ('fiveToTen', '5 - 10 years'), ('moreThanTen', 'More than 10 years')], default='', max_length=12),
        ),
    ]
