# Generated by Django 3.1.3 on 2020-11-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertApp', '0007_auto_20201110_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='approved',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
    ]
