# Generated by Django 3.1.3 on 2020-11-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertApp', '0008_auto_20201119_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='imageProfile',
            field=models.ImageField(blank=True, default='./mockWizProject/static/images/default.png', null=True, upload_to='expert/profilePicture'),
        ),
    ]
